library(BSDA)
library(car)
library(coxme)
library(e1071)
library(extrafont)
loadfonts()
library(Hmisc)
library(gtools)
library(kSamples) 
library(igraph)
library(lme4)
library(lmerTest)
library(MASS)
library(measurements)
library(metap)
library(multcomp)
library(nlme)
library(plotrix)
library(pls)
library(RColorBrewer)
library(scales)
library(spatstat)
library(stringr)
library(survival)
library(survcomp)
library(vioplot)
library(viridisLite)
# AW
require(report)
require(sjPlot)
require(lme4)
require(car)
require(MuMIn)


### AW # for plotting
require(RColorBrewer)
require(shades)
require(colorspace)
require(plotwidgets)
require(ggplot2)
require(ggnewscale)
require(gridExtra)
require(extrafont)
require(cowplot)
#library(Cairo) # to ensure working export to pdf with non-standard fonts
#font_add_google("Crimson Text", "crimson", db_cache = FALSE)
require(dplyr)
#font_import()

######library(showtext)
######showtext_auto()#must be called to indicate that showtext is going to be automatically invoked to draw text whenever a plot is created.

