library(BSDA)
library(car)
library(coxme)
library(e1071)
library(extrafont)
loadfonts()
library(Hmisc)
library(gtools)
library(kSamples) 
library(igraph)
library(lme4)
library(lmerTest)
library(measurements)
library(metap)
library(multcomp)
library(nlme)
library(plotrix)
library(pls)
library(RColorBrewer)
library(scales)
library(spatstat)
library(stringr)
library(survival)
library(survcomp)
library(vioplot)
library(viridisLite)

### AW # for plotting
require(RColorBrewer)
require(shades)
require(colorspace)
require(plotwidgets)
require(ggplot2)
require(ggnewscale)
require(extrafont)
#library(Cairo) # to ensure working export to pdf with non-standard fonts
library(showtext)
font_add_google("Crimson Text", "crimson", db_cache = FALSE)
showtext_auto()#must be called to indicate that showtext is going to be automatically invoked to draw text whenever a plot is created.
require(dplyr)
